export const companies = 

[{cid:1,company:"Cassin Inc",employees:1054,material:"Wood"},
{cid:2,company:"Koch Inc",employees:962,material:"Wood"},
{cid:3,company:"Legros-Haley",employees:318,material:"Vinyl"},
{cid:4,company:"Grant, Orn and Wisoky",employees:631,material:"Plexiglass"},
{cid:5,company:"Hills LLC",employees:898,material:"Wood"},
{cid:6,company:"Willms and Sons",employees:74,material:"Stone"},
{cid:7,company:"Doyle, Cremin and Walsh",employees:120,material:"Brass"},
{cid:8,company:"Smith, Jaskolski and Bergstrom",employees:1076,material:"Granite"},
{cid:9,company:"Frami, Barrows and Gutkowski",employees:706,material:"Aluminum"},
{cid:10,company:"Thiel LLC",employees:1107,material:"Brass"},
{cid:11,company:"Schultz, Wisozk and Watsica",employees:232,material:"Plexiglass"},
{cid:12,company:"Konopelski-Lind",employees:640,material:"Brass"},
{cid:13,company:"Kertzmann, Armstrong and Schumm",employees:701,material:"Plastic"},
{cid:14,company:"Cruickshank, Shields and Stark",employees:480,material:"Vinyl"},
{cid:15,company:"Jones, Kirlin and Abbott",employees:705,material:"Aluminum"},
{cid:16,company:"Brakus LLC",employees:128,material:"Aluminum"},
{cid:17,company:"Turcotte Group",employees:373,material:"Stone"},
{cid:18,company:"Braun Group",employees:179,material:"Stone"},
{cid:19,company:"Conroy and Sons",employees:435,material:"Brass"},
{cid:20,company:"Schmitt-Schroeder",employees:400,material:"Plexiglass"},
{cid:21,company:"Schuppe and Sons",employees:412,material:"Steel"},
{cid:22,company:"Feil, Kuphal and Windler",employees:1052,material:"Granite"},
{cid:23,company:"Tillman, Pollich and Haag",employees:946,material:"Rubber"},
{cid:24,company:"Gerlach and Sons",employees:164,material:"Plastic"},
{cid:25,company:"VonRueden-Reynolds",employees:609,material:"Plexiglass"},
{cid:26,company:"Murphy Inc",employees:451,material:"Vinyl"},
{cid:27,company:"Johns, Herzog and Legros",employees:943,material:"Aluminum"},
{cid:28,company:"Gulgowski Inc",employees:1009,material:"Stone"},
{cid:29,company:"Schamberger-Feil",employees:863,material:"Wood"},
{cid:30,company:"Frami-Hirthe",employees:1022,material:"Rubber"},
{cid:31,company:"Brekke, Kilback and Bradtke",employees:602,material:"Granite"},
{cid:32,company:"Denesik Group",employees:908,material:"Stone"},
{cid:33,company:"Schowalter, Schmeler and Borer",employees:762,material:"Plexiglass"},
{cid:34,company:"Considine LLC",employees:63,material:"Wood"},
{cid:35,company:"Hegmann, Boyle and Hahn",employees:473,material:"Vinyl"},
{cid:36,company:"Heller, Kilback and Rowe",employees:148,material:"Granite"},
{cid:37,company:"Altenwerth and Sons",employees:263,material:"Granite"},
{cid:38,company:"Medhurst-Gerlach",employees:1106,material:"Granite"},
{cid:39,company:"Rosenbaum Inc",employees:958,material:"Aluminum"},
{cid:40,company:"Shields LLC",employees:636,material:"Brass"},
{cid:41,company:"Jakubowski, Stokes and Kozey",employees:150,material:"Vinyl"},
{cid:42,company:"Brakus Inc",employees:460,material:"Steel"},
{cid:43,company:"Hackett and Sons",employees:991,material:"Glass"},
{cid:44,company:"Kassulke, Brown and Cronin",employees:75,material:"Vinyl"},
{cid:45,company:"Cummings-Schultz",employees:856,material:"Plastic"},
{cid:46,company:"Kirlin-Walker",employees:759,material:"Plexiglass"},
{cid:47,company:"Nader, Lakin and Hansen",employees:522,material:"Vinyl"},
{cid:48,company:"Wyman-Pagac",employees:470,material:"Stone"},
{cid:49,company:"Goldner, Osinski and Bruen",employees:820,material:"Plastic"},
{cid:50,company:"Kuvalis, Senger and Morar",employees:985,material:"Granite"},
{cid:51,company:"Gorczany LLC",employees:545,material:"Stone"},
{cid:52,company:"Brakus Inc",employees:622,material:"Plexiglass"},
{cid:53,company:"Jacobi, Wisoky and Jacobs",employees:699,material:"Aluminum"},
{cid:54,company:"Heidenreich, Deckow and Wehner",employees:88,material:"Granite"},
{cid:55,company:"Pagac, Gulgowski and Upton",employees:215,material:"Granite"},
{cid:56,company:"Wiza, Wehner and McGlynn",employees:869,material:"Aluminum"},
{cid:57,company:"Gutkowski, Breitenberg and Klein",employees:613,material:"Vinyl"},
{cid:58,company:"McKenzie-Kuvalis",employees:878,material:"Granite"},
{cid:59,company:"Turcotte and Sons",employees:709,material:"Wood"},
{cid:60,company:"Block and Sons",employees:1027,material:"Steel"},
{cid:61,company:"Larson, Walker and Ankunding",employees:977,material:"Wood"},
{cid:62,company:"Kohler, Paucek and Bruen",employees:913,material:"Aluminum"},
{cid:63,company:"Koepp-Marvin",employees:1111,material:"Steel"},
{cid:64,company:"Stamm, Smith and Heaney",employees:1111,material:"Vinyl"},
{cid:65,company:"Waelchi-Hayes",employees:395,material:"Vinyl"},
{cid:66,company:"Blick LLC",employees:350,material:"Rubber"},
{cid:67,company:"Langosh-Lueilwitz",employees:744,material:"Glass"},
{cid:68,company:"Bode, Ryan and Buckridge",employees:930,material:"Plexiglass"},
{cid:69,company:"Witting Group",employees:1080,material:"Granite"},
{cid:70,company:"Gleason-Fay",employees:421,material:"Brass"},
{cid:71,company:"Goldner-Schneider",employees:434,material:"Glass"},
{cid:72,company:"Price-Kub",employees:71,material:"Aluminum"},
{cid:73,company:"Schroeder-Bosco",employees:1105,material:"Aluminum"},
{cid:74,company:"Murazik Group",employees:1029,material:"Vinyl"},
{cid:75,company:"Homenick, Braun and Hermann",employees:739,material:"Glass"},
{cid:76,company:"Wolf Inc",employees:997,material:"Stone"},
{cid:77,company:"Lueilwitz, Rau and Crona",employees:546,material:"Rubber"},
{cid:78,company:"Crooks, Streich and Kerluke",employees:1087,material:"Wood"},
{cid:79,company:"Blanda-Hudson",employees:262,material:"Glass"},
{cid:80,company:"Beer-Becker",employees:700,material:"Stone"},
{cid:81,company:"Harber, Shanahan and Lebsack",employees:577,material:"Rubber"},
{cid:82,company:"Jones, Erdman and Roob",employees:1040,material:"Steel"},
{cid:83,company:"Wiza-Stokes",employees:826,material:"Brass"},
{cid:84,company:"Mertz, Ledner and Marks",employees:154,material:"Granite"},
{cid:85,company:"Lueilwitz-Barton",employees:587,material:"Stone"},
{cid:86,company:"Reinger, McGlynn and Ondricka",employees:723,material:"Rubber"},
{cid:87,company:"Price Group",employees:851,material:"Stone"},
{cid:88,company:"Rolfson-Hoeger",employees:314,material:"Vinyl"},
{cid:89,company:"Keebler Inc",employees:403,material:"Steel"},
{cid:90,company:"Dickinson, Walker and Klein",employees:667,material:"Wood"},
{cid:91,company:"Hessel, Crona and Huels",employees:415,material:"Aluminum"},
{cid:92,company:"Rogahn, Schulist and Stiedemann",employees:716,material:"Brass"},
{cid:93,company:"Kiehn-Mills",employees:594,material:"Glass"},
{cid:94,company:"Little, Nitzsche and Ratke",employees:408,material:"Rubber"},
{cid:95,company:"Ritchie-Okuneva",employees:205,material:"Steel"},
{cid:96,company:"O'Conner, Kub and Ledner",employees:519,material:"Granite"},
{cid:97,company:"Altenwerth, Wolff and Legros",employees:986,material:"Brass"},
{cid:98,company:"Hills, Wilkinson and Cummerata",employees:141,material:"Plastic"},
{cid:99,company:"Wintheiser-Mraz",employees:382,material:"Granite"},
{cid:100,company:"Stroman-Davis",employees:409,material:"Steel"}];